version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - crypto-net

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - crypto-net

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - crypto-net


  websocket-client:
    build:
      context: ./websocket-client
    container_name: websocket-client
    networks:
      - crypto-net

  spark-streaming:
    build:
      context: ./spark-streaming
    container_name: spark-streaming
    networks:
      - crypto-net

  fastapi-app:
    build:
      context: ./fastapi-app
    container_name: fastapi-app
    ports:
      - "8000:8000"
    networks:
      - crypto-net

networks:
  crypto-net:
    name: crypto-net
