version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - crypto-net

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - crypto-net

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - crypto-net

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crypto_db
    ports:
      - "5432:5432"
    networks:
      - crypto-net

  websocket-client:
    build:
      context: ./websocket-client
    networks:
      - crypto-net

  spark-streaming:
    build:
      context: ./spark-streaming
    networks:
      - crypto-net

  fastapi-app:
    build:
      context: ./fastapi-app
    ports:
      - "8000:8000"
    networks:
      - crypto-net

networks:
  crypto-net:
    external: true
